# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
#test: &default
#  STRIPE_PUBLISHABLE_KEY:	"pk_test_51K8QmuKagIQDGenET6qjzSMbUVaPeig4dcRJa7yBDURrMl1YlK8kvAGuwogWeS1G3KfWSpUUUbQAh1waACb7TkCS00AjBklEDK"
#  STRIPE_SECRET_KEY: 	"sk_test_51K8QmuKagIQDGenEdl6VQx1sapp9ln7c04KWIYNhKtT1ZiDOdaT0hbqsHuQRjuOyxJYIR2YOdLVU8SDj5aGi3CL3002b3iAH0A"
#development:
#  <<: *default

AWS_ACCESS_KEY: "AKIAUQ3IJZODPSP5OYMZ"
AWS_SECRET_KEY: "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"
AWS_BUCKET: "ceuiticol"